<?php

$wgCirrusSearchIndexBaseName = 'commons_image_quality';
$wgCirrusSearchFullTextQueryBuilderProfile = 'perfield_builder';
$wgCirrusSearchExtraIndexes = [];
$wgCirrusSearchLanguageWeight = [
	0 => 0,
	'user' => 0,
	'wiki' => 0
];

$wgNamespacesToBeSearchedDefault = [
	6 => 1,
	12 => 0,
	14 => 0,
	100 => 0,
	106 => 0,
	0 => 0,
	1 => 0,
	2 => 0,
	3 => 0,
	4 => 0,
	5 => 0,
	107 => 0,
	7 => 0,
	8 => 0,
	9 => 0,
	10 => 0,
	11 => 0,
	108 => 0,
	13 => 0
];
